<script>
/* 
- 간소화된 라우팅 임시 작성
  - (참고) https://v3-docs.vuejs-korea.org/guide/scaling-up/routing.html
- 쓸만한 라우팅은 vue-router 라이브러리 사용할 것
  - (참고) https://router.vuejs.kr/
*/
import VueAutoGeneratedExampleMain from "./components/vue-auto-generated-example/VueAutoGeneratedExampleMain.vue"
import HomePage from "./components/HomePage.vue"
import HelloVue from "./components/official-example/HelloVue.vue"

const routes = {
  "": HomePage,
  "auto-generated-example": VueAutoGeneratedExampleMain,
  "hello-view": HelloVue,
}

export default {
  data() {
    return {
      currentPath: window.location.hash
    }
  },
  computed: {
    currentView() {
      return routes[this.currentPath.slice(0).substr(1) || ""]
    }
  },
  mounted() {
    window.addEventListener("hashchange", () => {
      this.currentPath = window.location.hash
    })
  }
}
</script>

<template>
  <div>
    <a href="#">Home</a> | 
    <a href="#auto-generated-example">Vue.js auto generated example</a>
  </div>
  <div>
    예제 - 
    <a href="#hello-view">안녕 Vue</a>
  </div>
  <div id="view-area">
    <component :is="currentView" />
  </div>
</template>
