<script>
/* 
- 간소화된 라우팅 임시 작성
  - (참고) https://v3-docs.vuejs-korea.org/guide/scaling-up/routing.html
- 쓸만한 라우팅은 vue-router 라이브러리 사용할 것
  - (참고) https://router.vuejs.kr/
*/
import HomePage from "./components/HomePage.vue";
import VueAutoGeneratedExampleMain from "./components/vue-auto-generated-example/VueAutoGeneratedExampleMain.vue";
import HelloVue from "./components/official-example/HelloVue.vue";

const routes = {
  "": HomePage,
  "auto-generated-example": VueAutoGeneratedExampleMain,
  "hello-view": HelloVue,
}

export default {
  data() {
    return {
      currentPath: window.location.hash
    }
  },
  computed: {
    currentView() {
      return routes[this.currentPath.slice(0).substr(1) || ""]
    }
  },
  mounted() {
    window.addEventListener("hashchange", () => {
      this.currentPath = window.location.hash
    })
  }
}
</script>

<template>
  <div class="toc-area">
    <div class="toc">
      <a href="#">Home</a>
      <p>|</p>
      <a href="#auto-generated-example">Vue.js auto generated example</a>
    </div>
    <div class="toc">
      <p>예제</p>
      <p>||</p>
      <a href="#hello-view">안녕 Vue</a>
    </div>
  </div>
  <div id="view-area">
    <component :is="currentView" />
  </div>
</template>

<style scoped>
.toc-area {
  padding-bottom: 4px;
  border-bottom: 1px solid hsla(160, 100%, 37%, 0.5);
}

.toc {
  display: flex;
  
}

.toc>a {
  margin-bottom: 10px;
}

#view-area {
  width: 100%;
  display: flex;
  justify-content: center;
  margin: 0 auto;
  margin-top: 32px;
}
</style>
